const MAIN_SPREAD = '1s-X5HmWiACl_msyq1ZPdMD0ATfB_YgcDO8GhXlcUa3s';
const MAIN_SHEET = 'Main';
const FORM_SHEET = 'Form';
const SCORES_FOLDER = '19FwqKmM-UzkHipGOetA6VP0Fujt9iajt';

const ERROR_RANGE = "C1";
const FOLDER_RANGE = "A1";
const FORM_ERROR_RANGE = "D2";

const TITLE_RANGE = "B2";
const COMPOSER_RANGE = "B4";
const LYRICS_RANGE = "B6";
const ARRANGER_RANGE = "B8";
const ID_RANGE = "B10";

const FORM_ACTIONS_RANGE = "B12";

const RESPONSE_COL = 7;
const RESPONSE_RANGE = "G2";

const HALF_INCH_IN_POINTS = inchesToPoints(0.5);

// DOCUMENT STYLES
const DOCUMENT_STYLE = {};
DOCUMENT_STYLE[DocumentApp.Attribute.MARGIN_TOP] = HALF_INCH_IN_POINTS;
DOCUMENT_STYLE[DocumentApp.Attribute.MARGIN_LEFT] = HALF_INCH_IN_POINTS;
DOCUMENT_STYLE[DocumentApp.Attribute.MARGIN_RIGHT] = HALF_INCH_IN_POINTS;
DOCUMENT_STYLE[DocumentApp.Attribute.MARGIN_BOTTOM] = HALF_INCH_IN_POINTS;

